allowBuilds:
  '@firebase/util': set this to true or false
  '@serialport/bindings-cpp': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  tesseract.js: set this to true or false
